baseURL = "http://example.org/"
languageCode = "es"
title = "R-Tecno"
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "contacto"
    title = "contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0